//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SenpaiCopy.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string LastSelectedImagePath {
            get {
                return ((string)(this["LastSelectedImagePath"]));
            }
            set {
                this["LastSelectedImagePath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string LastSelectedFolderPath {
            get {
                return ((string)(this["LastSelectedFolderPath"]));
            }
            set {
                this["LastSelectedFolderPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int PreviousHotkey {
            get {
                return ((int)(this["PreviousHotkey"]));
            }
            set {
                this["PreviousHotkey"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int ExecuteHotkey {
            get {
                return ((int)(this["ExecuteHotkey"]));
            }
            set {
                this["ExecuteHotkey"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int NextHotkey {
            get {
                return ((int)(this["NextHotkey"]));
            }
            set {
                this["NextHotkey"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int ClearCheckBoxesHotkey {
            get {
                return ((int)(this["ClearCheckBoxesHotkey"]));
            }
            set {
                this["ClearCheckBoxesHotkey"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(".bmp;.gif;.ico;.jpg;.jpeg;.png;.tif;.tiff;.webm;.wmp")]
        public string SupportedFormats {
            get {
                return ((string)(this["SupportedFormats"]));
            }
            set {
                this["SupportedFormats"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(".bmp;.gif;.jpg;.jpeg;.png;.tiff;.webm;.wmp")]
        public string EnabledFormats {
            get {
                return ((string)(this["EnabledFormats"]));
            }
            set {
                this["EnabledFormats"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool EnableStatisticTracking {
            get {
                return ((bool)(this["EnableStatisticTracking"]));
            }
            set {
                this["EnableStatisticTracking"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int DeletedImagesStatistic {
            get {
                return ((int)(this["DeletedImagesStatistic"]));
            }
            set {
                this["DeletedImagesStatistic"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int CopiedImagesStatistic {
            get {
                return ((int)(this["CopiedImagesStatistic"]));
            }
            set {
                this["CopiedImagesStatistic"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double DeletedImagesSizeStatistic {
            get {
                return ((double)(this["DeletedImagesSizeStatistic"]));
            }
            set {
                this["DeletedImagesSizeStatistic"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double CopiedImagesSizeStatistic {
            get {
                return ((double)(this["CopiedImagesSizeStatistic"]));
            }
            set {
                this["CopiedImagesSizeStatistic"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int StartupStatistic {
            get {
                return ((int)(this["StartupStatistic"]));
            }
            set {
                this["StartupStatistic"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int TotalCopiedImagesStatistic {
            get {
                return ((int)(this["TotalCopiedImagesStatistic"]));
            }
            set {
                this["TotalCopiedImagesStatistic"] = value;
            }
        }
    }
}
